sonar.sources=src,server
sonar.exclusions=**/node_modules/**,**/dist/**,backend/**,server/index.js,server/migrate.js,server/initDb.js,server/createAdmin.js,server/export_defaults.js,server/defaultQuestions.js,server/db.js,**/*.test.*,**/*.spec.*
sonar.cpd.exclusions=**/node_modules/**,**/dist/**,backend/**,src/data/questions.js
